is_debug: true
listen:
  # type: sock
  type: port
  bind_ip: 0.0.0.0
  port: 10000
users:
  host: localhost
  port: 27017
  database: user-service
  auth_db: 
  username: root
  password: password
  collection: users
  indexes:  
      - email