###

GET http://localhost:10000/users/123
Content-Type: application/json

###

GET http://localhost:10000/users
Content-Type: application/json

###

POST http://localhost:10000/users
Content-Type: application/json

###

PUT http://localhost:10000/users/1
Content-Type: application/json

{}

###

PATCH http://localhost:10000/users/1
Content-Type: application/json

{}

###

DELETE http://localhost:10000/users/1
Content-Type: application/json

{}
